# Generated by Django 5.1.3 on 2024-11-19 07:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('v', models.CharField(max_length=200)),
                ('invoice_no', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('c_n', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('d_n', models.CharField(max_length=200)),
                ('way', models.CharField(max_length=200)),
                ('fr', models.CharField(max_length=200)),
                ('to', models.CharField(max_length=200)),
                ('guest', models.CharField(max_length=500)),
                ('base_fare', models.CharField(max_length=200)),
                ('dis', models.CharField(max_length=200)),
                ('toll', models.CharField(max_length=200)),
                ('igst', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=200)),
                ('wallet', models.CharField(max_length=200)),
                ('cash', models.CharField(max_length=200)),
                ('online', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('makers_name', models.CharField(max_length=200)),
                ('registration_no', models.CharField(max_length=100)),
                ('registration_date', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=100)),
                ('avg_fuel', models.PositiveBigIntegerField(default=0, null=True)),
                ('meter_reading', models.PositiveBigIntegerField(null=True)),
                ('seating_capacity', models.PositiveBigIntegerField()),
                ('insu_start', models.DateField()),
                ('insu_end', models.DateField()),
                ('pop_start', models.DateField()),
                ('pop_end', models.DateField()),
                ('fit_start', models.DateField()),
                ('fit_end', models.DateField()),
                ('rc', models.ImageField(upload_to='media/rc')),
                ('insu_image', models.ImageField(upload_to='media/insu_image')),
                ('pop_image', models.ImageField(upload_to='media/pop_image')),
                ('fit_image', models.ImageField(upload_to='media/fit_image')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Driver')], default=1, max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.PositiveBigIntegerField()),
                ('fuel_consumed', models.PositiveBigIntegerField()),
                ('last_fuel_avg', models.FloatField(null=True)),
                ('v', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fuel_entries', to='car.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='daily_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_km', models.CharField(max_length=100)),
                ('out_km', models.CharField(max_length=100)),
                ('v', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('work', models.CharField(max_length=500)),
                ('vendor', models.CharField(max_length=200)),
                ('amount', models.PositiveBigIntegerField()),
                ('status', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='media/maintinance')),
                ('v', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car.vehicle')),
            ],
        ),
    ]
