# Generated by Django 5.1.3 on 2024-11-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuel',
            old_name='last_fuel_avg',
            new_name='avg',
        ),
    ]
