# Generated by Django 5.1.3 on 2024-11-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_rename_last_fuel_avg_fuel_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
