# Generated by Django 5.1.3 on 2024-11-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_fuel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_report',
            name='date',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
