# Generated by Django 5.1.3 on 2024-11-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_daily_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_report',
            name='total_r',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
