# Generated by Django 5.1.3 on 2024-11-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_daily_report_total_r'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
