# Generated by Django 5.1.3 on 2024-11-27 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_fuel_amount_fuel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='base_fare',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='d_n',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='dis',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='fr',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='to',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='toll',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='v',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='way',
        ),
        migrations.AddField(
            model_name='bill',
            name='add',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='bill',
            name='email',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='bill',
            name='mob',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.CreateModel(
            name='VehicleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.CharField(max_length=200)),
                ('base_fare', models.CharField(default='0', max_length=200)),
                ('dis', models.CharField(default='0', max_length=200)),
                ('toll', models.CharField(default='0', max_length=200)),
                ('igst', models.CharField(default='0', max_length=200)),
                ('d_n', models.CharField(max_length=200)),
                ('way', models.CharField(max_length=200)),
                ('fr', models.CharField(max_length=200)),
                ('to', models.CharField(max_length=200)),
                ('guest', models.CharField(max_length=500)),
                ('total', models.CharField(max_length=200)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='car.bill')),
            ],
        ),
    ]
