# Generated by Django 5.1.3 on 2024-11-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_remove_bill_base_fare_remove_bill_d_n_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='g_t',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='bill',
            name='c_n',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cash',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='bill',
            name='online',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='bill',
            name='wallet',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
