# Generated by Django 5.1.3 on 2024-11-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_bill_g_t_alter_bill_c_n_alter_bill_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetail',
            name='date',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
