# Generated by Django 5.1.3 on 2024-11-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_vehicledetail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
