# Generated by Django 5.1.3 on 2024-12-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_bill_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetail',
            name='Ekm',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='vehicledetail',
            name='Exh',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='vehicledetail',
            name='aph',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='vehicledetail',
            name='apk',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='vehicledetail',
            name='pph',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='vehicledetail',
            name='ppk',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
