# Generated by Django 5.1.3 on 2024-12-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_vehicledetail_ekm_vehicledetail_exh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='fit_end',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='fit_image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='fit_start',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insu_end',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insu_image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insu_start',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='makers_name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='pop_end',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='pop_image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='pop_start',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='seating_capacity',
        ),
    ]
