# Generated by Django 5.1.3 on 2024-12-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_remove_vehicle_fit_end_remove_vehicle_fit_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_report',
            name='add',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='daily_report',
            name='name',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
