# Generated by Django 5.1.3 on 2024-12-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_daily_report_add_daily_report_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetail',
            name='km',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
