# Generated by Django 5.1.3 on 2024-12-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_vehicledetail_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetail',
            name='date',
            field=models.DateField(),
        ),
    ]
