# Generated by Django 5.1.3 on 2024-12-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_alter_vehicledetail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='date',
            field=models.DateField(),
        ),
    ]
