# Generated by Django 5.1.3 on 2025-07-13 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_alter_fuel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adv_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust', models.CharField(max_length=300)),
                ('fr', models.CharField(max_length=200)),
                ('to', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=300)),
                ('number', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='media/vendorbill')),
                ('vendor', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=200)),
                ('invoice', models.CharField(max_length=300)),
                ('amount', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/BillBook')),
                ('cust', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=200)),
                ('invoice', models.CharField(max_length=300)),
                ('amount', models.PositiveBigIntegerField()),
                ('v', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Bill_Book', to='car.vehicle')),
            ],
        ),
    ]
