# Generated by Django 5.2.4 on 2025-08-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0017_adv_book_vendor_bill_bill_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv_book',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adv_book',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='adv_book',
            name='cust',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adv_book',
            name='fr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adv_book',
            name='number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='adv_book',
            name='to',
            field=models.CharField(max_length=100),
        ),
    ]
