# Generated by Django 5.2.4 on 2025-08-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0018_adv_book_time_alter_adv_book_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='terms_and_conditions',
            field=models.TextField(default='E. & O.E. Subject to Delhi Jurisdiction.\nOur Responsibility of the signed duty slip resets till we handover them to you with the bill.\nInterest chargable on bills not paid on presentation @ 18% p.a.\nPassengers Tax, Toll tax, Interstate taxes, Car parking Etc. will be charged on actual basis on production of receipts.\nGST, if Applicable will be charged extra. A subsequent bill will be issued for the same.\nIn case of discrepency , Kindly return the bill for necessary correction within 10 days or it shall be treated as O.K. and you shall be liable to pay the full amount.\nCustomer Support: For any issues or support related to the services, please contact us directly at 98916 71848.'),
        ),
    ]
