# Generated by Django 5.2.4 on 2025-10-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0019_bill_terms_and_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='terms_and_conditions',
            field=models.TextField(null=True),
        ),
    ]
