# Generated by Django 5.2.8 on 2025-11-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0020_alter_bill_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetail',
            name='night',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
